[package]
name = "progress-clocks"
version = "0.2.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.4.2", features = ["wasm_js"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4", "fast-rng", "rng-getrandom", "serde"] }
wasm-bindgen = "0.2.118"
web-sys = { version = "0.3.95", features = ["Window", "Document", "Node", "Element", "HtmlElement", "HtmlInputElement", "HtmlDivElement", "PointerEvent", "CssStyleDeclaration", "HtmlCanvasElement", "CanvasRenderingContext2d", "HtmlButtonElement", "DomTokenList", "HtmlCollection", "Path2d", "DomRect", "HtmlAnchorElement"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
